#
# Makefile	Radius Makefile for BSD/OS
#
#

CC	= gcc
CFLAGS	= -Wall -g
LDFLAGS	= # -s
LIBS	=
LCRYPT	=

# Set these to the correct values if you want DBM support.
# BSDi has DB support in the C library, no -ldb needed.
DBM     = -DUSE_DB1
DBMLIB  =

# BSDi ha no PAM support.
#PAM	= -DPAM
#PAMLIB	= -lpam

INSTALL = install
DINSTALL = mkdir -p

BINDIR  = /usr/local/bin
SBINDIR = /usr/local/sbin
MANDIR  = /usr/local/man

.include "Make.inc"
