#
# Makefile      Radius Makefile for AIX
#
# submitted by Ewan Leith <ejl@man.fraser-williams.com>
#

CC      = gcc
CFLAGS  = -Wall -g -DNOSHADOW -Daix # -DSPECIALIX_JETSTREAM_HACK
LDFLAGS = # -s
LIBS    =
LCRYPT  = -lcrypt

# Set these to the correct values if you want DBM support.
#DBM     = -DUSE_NDBM
#DBMLIB  = #-ldb

#PAM    = -DPAM
#PAMLIB = -lpam

INSTALL = installbsd
DINSTALL = mkdir -p

BINDIR  = /usr/local/bin
SBINDIR = /usr/local/sbin
MANDIR  = /usr/local/man

include Make.inc
