#
# Makefile	Radius Makefile for OSF/Unix (Digital)
#
#		Add "-DOSFC2" to CFLAGS and "-lsecurity" to LIBS
#		if you want to compile for OSF with C2 security
#

CC	= cc
CFLAGS	= -DOSFSIA -DNOSHADOW
LDFLAGS	= # -s
LIBS	= 
LCRYPT	=

# Set these to the correct values if you want DBM support.
#DBM     = -DUSE_NDBM
#DBMLIB  = -ldb

#PAM	= -DPAM
#PAMLIB	= -lpam

INSTALL = install
DINSTALL = install -d

BINDIR  = /usr/local/bin
SBINDIR = /usr/local/sbin
MANDIR  = /usr/local/man

include Make.inc
