#
# Makefile	Radius Makefile for HP/UX
#
#

CC	= gcc
CFLAGS	= -Wall -g -DNOSHADOW
LDFLAGS	= # -s
LIBS	=
LCRYPT	=

# Set these to the correct values if you want DBM support.
#DBM     = -DUSE_NDBM
#DBMLIB  = #-ldb

#PAM	= -DPAM
#PAMLIB	= -lpam

INSTALL = install
DINSTALL = install -d

BINDIR  = /usr/local/bin
SBINDIR = /usr/local/sbin
MANDIR  = /usr/local/man

include "Make.inc"
