CREATE TABLE IF NOT EXISTS trafgroup (
	h0 float NOT NULL default '0',
	h1 float NOT NULL default '0',
	h2 float NOT NULL default '0',
	h3 float NOT NULL default '0',
	h4 float NOT NULL default '0',
	h5 float NOT NULL default '0',
	h6 float NOT NULL default '0',
	h7 float NOT NULL default '0',
	h8 float NOT NULL default '0',
	h9 float NOT NULL default '0',
	h10 float NOT NULL default '0',
	h11 float NOT NULL default '0',
	h12 float NOT NULL default '0',
	h13 float NOT NULL default '0',
	h14 float NOT NULL default '0',
	h15 float NOT NULL default '0',
	h16 float NOT NULL default '0',
	h17 float NOT NULL default '0',
	h18 float NOT NULL default '0',
	h19 float NOT NULL default '0',
	h20 float NOT NULL default '0',
	h21 float NOT NULL default '0',
	h22 float NOT NULL default '0',
	h23 float NOT NULL default '0',
	week smallint(1) NOT NULL default '0',
	gid smallint(5) NOT NULL default '999'
) TYPE=MyISAM;
